//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumiTracker.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LumiTracker.Config.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deck.
        /// </summary>
        public static string AddNewDeck {
            get {
                return ResourceManager.GetString("AddNewDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LumiTracker.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Path.
        /// </summary>
        public static string AppPath {
            get {
                return ResourceManager.GetString("AppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin TCG Deck Tracker.
        /// </summary>
        public static string AppSubTitle {
            get {
                return ResourceManager.GetString("AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Active Deck.
        /// </summary>
        public static string AutoSelectActiveDeck {
            get {
                return ResourceManager.GetString("AutoSelectActiveDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. When the duel starts, LumiTracker will detect our three characters and search for the matching deck in the list above.
        ///2. If there are decks with the same characters, the one that was most recently modified will be chosen; decks with different character orders will be regarded as separate.
        ///3. The active deck will be highlighted..
        /// </summary>
        public static string AutoSelectActiveDeck_ToolTip {
            get {
                return ResourceManager.GetString("AutoSelectActiveDeck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilibili.
        /// </summary>
        public static string BiliBiliLink {
            get {
                return ResourceManager.GetString("BiliBiliLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Version.
        /// </summary>
        public static string BuildVersion {
            get {
                return ResourceManager.GetString("BuildVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Window.
        /// </summary>
        public static string CanvasWindowTitle {
            get {
                return ResourceManager.GetString("CanvasWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Type.
        /// </summary>
        public static string CaptureType {
            get {
                return ResourceManager.GetString("CaptureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * This is the only available method for cloud game.
        /// </summary>
        public static string CaptureType_CloudGameHint {
            get {
                return ResourceManager.GetString("CaptureType_CloudGameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Only supports Chrome, Firefox, or Edge browsers with fullscreen mode.
        /// </summary>
        public static string CaptureType_CloudGameHint_Web {
            get {
                return ResourceManager.GetString("CaptureType_CloudGameHint_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Resolution : .
        /// </summary>
        public static string CaptureType_FrameSizePrompt {
            get {
                return ResourceManager.GetString("CaptureType_FrameSizePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string CaptureType_Test {
            get {
                return ResourceManager.GetString("CaptureType_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Updates on Startup.
        /// </summary>
        public static string CheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Client.
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CN] Cloud PC.
        /// </summary>
        public static string ClientType_CloudPC {
            get {
                return ResourceManager.GetString("ClientType_CloudPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CN] Cloud Web.
        /// </summary>
        public static string ClientType_CloudWeb {
            get {
                return ResourceManager.GetString("ClientType_CloudWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Global] Genshin.
        /// </summary>
        public static string ClientType_Global {
            get {
                return ResourceManager.GetString("ClientType_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CN] YuanShen.
        /// </summary>
        public static string ClientType_YuanShen {
            get {
                return ResourceManager.GetString("ClientType_YuanShen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Behavior.
        /// </summary>
        public static string ClosingBehavior {
            get {
                return ResourceManager.GetString("ClosingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to System Tray.
        /// </summary>
        public static string ClosingBehavior_Minimize {
            get {
                return ResourceManager.GetString("ClosingBehavior_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ClosingBehavior_Quit {
            get {
                return ResourceManager.GetString("ClosingBehavior_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string ClosingDialogTitle {
            get {
                return ResourceManager.GetString("ClosingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing Code copied to the clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersion_Title {
            get {
                return ResourceManager.GetString("CurrentVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string DeckPageTitle {
            get {
                return ResourceManager.GetString("DeckPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string DeckTab_Cards {
            get {
                return ResourceManager.GetString("DeckTab_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string DeckTab_Games {
            get {
                return ResourceManager.GetString("DeckTab_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck Window.
        /// </summary>
        public static string DeckWindowTitle {
            get {
                return ResourceManager.GetString("DeckWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Untitled&gt;.
        /// </summary>
        public static string DefaultDeckName {
            get {
                return ResourceManager.GetString("DefaultDeckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        public static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Builds.
        /// </summary>
        public static string DeleteConfirm_All {
            get {
                return ResourceManager.GetString("DeleteConfirm_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Build.
        /// </summary>
        public static string DeleteConfirm_Current {
            get {
                return ResourceManager.GetString("DeleteConfirm_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Deck：.
        /// </summary>
        public static string DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This duel record will be irrecoverable after deletion. Do you want to continue?.
        /// </summary>
        public static string DeleteConfirm_RecordMessage {
            get {
                return ResourceManager.GetString("DeleteConfirm_RecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDeck {
            get {
                return ResourceManager.GetString("DeleteDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string DocumentationLink {
            get {
                return ResourceManager.GetString("DocumentationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Giving ! .
        /// </summary>
        public static string Donate_ButtonText {
            get {
                return ResourceManager.GetString("Donate_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you found this useful, a donation would be appreciated~.
        /// </summary>
        public static string Donate_Prompt {
            get {
                return ResourceManager.GetString("Donate_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Supporting! Your Generosity Brightens My Day!.
        /// </summary>
        public static string Donate_Thanks {
            get {
                return ResourceManager.GetString("Donate_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string Duel {
            get {
                return ResourceManager.GetString("Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        public static string EditDeckName {
            get {
                return ResourceManager.GetString("EditDeckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Deck Name Here.
        /// </summary>
        public static string EditDeckName_Placeholder {
            get {
                return ResourceManager.GetString("EditDeckName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Deck Name.
        /// </summary>
        public static string EditDeckName_Title {
            get {
                return ResourceManager.GetString("EditDeckName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackLink {
            get {
                return ResourceManager.GetString("FeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is open-source and completely free. If you paid for it, you have been scammed!.
        /// </summary>
        public static string FreeDeclaration {
            get {
                return ResourceManager.GetString("FreeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Link.
        /// </summary>
        public static string FriendLink {
            get {
                return ResourceManager.GetString("FriendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel Not Started.
        /// </summary>
        public static string GameNotStarted {
            get {
                return ResourceManager.GetString("GameNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting game window....
        /// </summary>
        public static string GameWatcherState_NoWindowFound {
            get {
                return ResourceManager.GetString("GameWatcherState_NoWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching LumiTracker....
        /// </summary>
        public static string GameWatcherState_StartingWindowWatcher {
            get {
                return ResourceManager.GetString("GameWatcherState_StartingWindowWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LumiTracker started.
        /// </summary>
        public static string GameWatcherState_WindowWatcherStarted {
            get {
                return ResourceManager.GetString("GameWatcherState_WindowWatcherStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string GithubLink {
            get {
                return ResourceManager.GetString("GithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Sharing Code.
        /// </summary>
        public static string ImportDeck_Placeholder {
            get {
                return ResourceManager.GetString("ImportDeck_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Sharing Code to import deck.
        /// </summary>
        public static string ImportDeck_Title {
            get {
                return ResourceManager.GetString("ImportDeck_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If duel not detected, consider trying a different capture method;.
        /// </summary>
        public static string Instruction1 {
            get {
                return ResourceManager.GetString("Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not minimize the game window! Capture is not available when minimized;.
        /// </summary>
        public static string Instruction2 {
            get {
                return ResourceManager.GetString("Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If fullscreen, change &quot;Fullscreen&quot; to &quot;Borderless&quot; in Genshin&apos;s Settings -&gt; Graphics -&gt; Display Mode..
        /// </summary>
        public static string Instruction3 {
            get {
                return ResourceManager.GetString("Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sharing Code:.
        /// </summary>
        public static string InvalidSharingCode_Message {
            get {
                return ResourceManager.GetString("InvalidSharingCode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the Sharing Code.
        /// </summary>
        public static string InvalidSharingCode_Title {
            get {
                return ResourceManager.GetString("InvalidSharingCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string LatestRelease_Title {
            get {
                return ResourceManager.GetString("LatestRelease_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        public static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture is not possible when the game window is minimized!.
        /// </summary>
        public static string MinimizedNotification {
            get {
                return ResourceManager.GetString("MinimizedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Deck.
        /// </summary>
        public static string MyDeck {
            get {
                return ResourceManager.GetString("MyDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Played.
        /// </summary>
        public static string MyPlayedCards {
            get {
                return ResourceManager.GetString("MyPlayedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        public static string Notices {
            get {
                return ResourceManager.GetString("Notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this again.
        /// </summary>
        public static string NotShowAgain {
            get {
                return ResourceManager.GetString("NotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator Server.
        /// </summary>
        public static string OB_AppSubTitle {
            get {
                return ResourceManager.GetString("OB_AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string OB_ChangeDir {
            get {
                return ResourceManager.GetString("OB_ChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server.
        /// </summary>
        public static string OB_ConnectBtnText {
            get {
                return ResourceManager.GetString("OB_ConnectBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string OB_GameNotStarted {
            get {
                return ResourceManager.GetString("OB_GameNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game.
        /// </summary>
        public static string OB_GameStarted {
            get {
                return ResourceManager.GetString("OB_GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string OB_Header_Connected {
            get {
                return ResourceManager.GetString("OB_Header_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Status.
        /// </summary>
        public static string OB_Header_GameStarted {
            get {
                return ResourceManager.GetString("OB_Header_GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string OB_Header_Name {
            get {
                return ResourceManager.GetString("OB_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string OB_Host {
            get {
                return ResourceManager.GetString("OB_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address Copied to Clipboard.
        /// </summary>
        public static string OB_HostCopiedToClipboard {
            get {
                return ResourceManager.GetString("OB_HostCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Directory.
        /// </summary>
        public static string OB_IconDirectory {
            get {
                return ResourceManager.GetString("OB_IconDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Icon Count.
        /// </summary>
        public static string OB_MaxTokens {
            get {
                return ResourceManager.GetString("OB_MaxTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My View.
        /// </summary>
        public static string OB_MyView {
            get {
                return ResourceManager.GetString("OB_MyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT ID.
        /// </summary>
        public static string OB_NatId {
            get {
                return ResourceManager.GetString("OB_NatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent&apos;s View.
        /// </summary>
        public static string OB_OpView {
            get {
                return ResourceManager.GetString("OB_OpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string OB_Port {
            get {
                return ResourceManager.GetString("OB_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Started.
        /// </summary>
        public static string OB_ServerStarted {
            get {
                return ResourceManager.GetString("OB_ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Starting....
        /// </summary>
        public static string OB_ServerStarting {
            get {
                return ResourceManager.GetString("OB_ServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectate.
        /// </summary>
        public static string OB_SettingsText {
            get {
                return ResourceManager.GetString("OB_SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string OBConnectState_Connected {
            get {
                return ResourceManager.GetString("OBConnectState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string OBConnectState_Connecting {
            get {
                return ResourceManager.GetString("OBConnectState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string OBConnectState_Failed {
            get {
                return ResourceManager.GetString("OBConnectState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string OBConnectState_None {
            get {
                return ResourceManager.GetString("OBConnectState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        public static string OBConnectState_Reconnecting {
            get {
                return ResourceManager.GetString("OBConnectState_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op Played.
        /// </summary>
        public static string OpPlayedCards {
            get {
                return ResourceManager.GetString("OpPlayedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string ReimportDeck {
            get {
                return ResourceManager.GetString("ReimportDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Modified Deck.
        /// </summary>
        public static string ReimportDeck_Title {
            get {
                return ResourceManager.GetString("ReimportDeck_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will take effect the next time you open the app. Would you like to restart now?.
        /// </summary>
        public static string Restart_Prompt {
            get {
                return ResourceManager.GetString("Restart_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App.
        /// </summary>
        public static string Restart_Title {
            get {
                return ResourceManager.GetString("Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        public static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LumiTracker uses computer vision without reading or modifying the game&apos;s memory..
        /// </summary>
        public static string SafeDeclaration {
            get {
                return ResourceManager.GetString("SafeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Active.
        /// </summary>
        public static string SetAsActiveDeck {
            get {
                return ResourceManager.GetString("SetAsActiveDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Active Deck:.
        /// </summary>
        public static string SetAsActiveSuccess_Message {
            get {
                return ResourceManager.GetString("SetAsActiveSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SetAsActiveSuccess_Title {
            get {
                return ResourceManager.GetString("SetAsActiveSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareDeck {
            get {
                return ResourceManager.GetString("ShareDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display UI outside the window.
        /// </summary>
        public static string ShowUIOutside {
            get {
                return ResourceManager.GetString("ShowUIOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Stats_AvgDuration {
            get {
                return ResourceManager.GetString("Stats_AvgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string Stats_AvgRounds {
            get {
                return ResourceManager.GetString("Stats_AvgRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Stats_Games {
            get {
                return ResourceManager.GetString("Stats_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Records Before Imported.
        /// </summary>
        public static string Stats_HideExpired {
            get {
                return ResourceManager.GetString("Stats_HideExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include All Build Versions.
        /// </summary>
        public static string Stats_IncludeAllBuildVersions {
            get {
                return ResourceManager.GetString("Stats_IncludeAllBuildVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Stats_Minute {
            get {
                return ResourceManager.GetString("Stats_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Stats_OtherMatchups {
            get {
                return ResourceManager.GetString("Stats_OtherMatchups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Rate.
        /// </summary>
        public static string Stats_WinRate {
            get {
                return ResourceManager.GetString("Stats_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Preview Release Channel.
        /// </summary>
        public static string SubscribeToBetaUpdates {
            get {
                return ResourceManager.GetString("SubscribeToBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Deck.
        /// </summary>
        public static string SubTab_InDeck {
            get {
                return ResourceManager.GetString("SubTab_InDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string SubTab_Played {
            get {
                return ResourceManager.GetString("SubTab_Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.summoners.top/en.
        /// </summary>
        public static string SummonersTop_URL {
            get {
                return ResourceManager.GetString("SummonersTop_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported aspect ratios:
        ///- 16:9
        ///- 16:10
        ///- 21:9 series (including 64:27, 43:18, 12:5).
        /// </summary>
        public static string SupportedRatioInfo {
            get {
                return ResourceManager.GetString("SupportedRatioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cards.
        /// </summary>
        public static string Tab_MyCards {
            get {
                return ResourceManager.GetString("Tab_MyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Tab_OpCards {
            get {
                return ResourceManager.GetString("Tab_OpCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Tray_Home {
            get {
                return ResourceManager.GetString("Tray_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Tray_Quit {
            get {
                return ResourceManager.GetString("Tray_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Card.
        /// </summary>
        public static string UnknownCard {
            get {
                return ResourceManager.GetString("UnknownCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Deck.
        /// </summary>
        public static string UnknownDeck {
            get {
                return ResourceManager.GetString("UnknownDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current resolution of game window is not supported..
        /// </summary>
        public static string UnsupportedRatioWarning {
            get {
                return ResourceManager.GetString("UnsupportedRatioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already latest.
        /// </summary>
        public static string UpdatePrompt_AlreadyLatest {
            get {
                return ResourceManager.GetString("UpdatePrompt_AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release History.
        /// </summary>
        public static string UpdatePrompt_ChangeLog {
            get {
                return ResourceManager.GetString("UpdatePrompt_ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release History (Preview).
        /// </summary>
        public static string UpdatePrompt_ChangeLogBeta {
            get {
                return ResourceManager.GetString("UpdatePrompt_ChangeLogBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string UpdatePrompt_CheckForUpdate {
            get {
                return ResourceManager.GetString("UpdatePrompt_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complete!.
        /// </summary>
        public static string UpdatePrompt_Complete {
            get {
                return ResourceManager.GetString("UpdatePrompt_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string UpdatePrompt_Connecting {
            get {
                return ResourceManager.GetString("UpdatePrompt_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed some known issues..
        /// </summary>
        public static string UpdatePrompt_DefaultPatchLog {
            get {
                return ResourceManager.GetString("UpdatePrompt_DefaultPatchLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string UpdatePrompt_Downloading {
            get {
                return ResourceManager.GetString("UpdatePrompt_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed, please retry; If still fails, try to run as Admin..
        /// </summary>
        public static string UpdatePrompt_Failed {
            get {
                return ResourceManager.GetString("UpdatePrompt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching latest version....
        /// </summary>
        public static string UpdatePrompt_Fetching {
            get {
                return ResourceManager.GetString("UpdatePrompt_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string UpdatePrompt_Later {
            get {
                return ResourceManager.GetString("UpdatePrompt_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Update.
        /// </summary>
        public static string UpdatePrompt_Manual {
            get {
                return ResourceManager.GetString("UpdatePrompt_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error, Retrying....
        /// </summary>
        public static string UpdatePrompt_Retrying {
            get {
                return ResourceManager.GetString("UpdatePrompt_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking....
        /// </summary>
        public static string UpdatePrompt_Unpacking {
            get {
                return ResourceManager.GetString("UpdatePrompt_Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string UpdatePrompt_UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdatePrompt_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Now.
        /// </summary>
        public static string UpdatePrompt_UpdateNow {
            get {
                return ResourceManager.GetString("UpdatePrompt_UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory.
        /// </summary>
        public static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to LumiTracker !.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
